services:
  - type: web
    name: my-line-bot
    env: python
    region: singapore
    plan: free
    branch: master
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    autoDeploy: true
    healthCheckPath: /